spring:
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
    sampler:
      probability: 1
  application:
    name: product-service
---
spring:
  profiles: product-service-1
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
---
spring:
  profiles: product-service-2
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/