server:
  port: 8084

spring:
  zipkin:
    base-url: http://ServiceChainTrace/
  sleuth:
    sampler:
      probability: 1
  application:
    name: ServiceChainTrace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false